name: mern-app

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306" 
    networks:
      - mern-app
    volumes:
      - mysql_data:/var/lib/mysql 

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"  # Jenkins UI port
      - "50000:50000"  # For agent connections
    networks:
      - mern-app
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data

  api:
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - mern-app
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
      target: production
      args:
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - mern-app
    depends_on:
      - api
  dashboard:
    build:
      context: ./dashboard
      target: production
      args:
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - mern-app
    depends_on:
      - frontend

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern-app
    depends_on:
      - frontend
      - api

volumes:
  mysql_data:
    driver: local
  caddy_data:
  caddy_config:
  jenkins_home:

networks:
  mern-app:
    driver: bridge
