name: deployer

services:
  jenkins:
    build: 
      context: ./jenkins
      dockerfile: DockerFile
    ports:
    - "8080:8080"
    - "50000:50000"
    networks:
    - jen-app
    volumes:
    - jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - jen-app
    depends_on:
      - jenkins

volumes:
  caddy_data:
  caddy_config:
  jenkins_home:

networks:
  jen-app:
    driver: bridge
