name: deployer
services: 
# dev services
  api-dev:
    build:
      context: ./api-dev
      target: production
    restart: unless-stopped
    env_file:
      - ./api-dev/.env
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - jen-app

  frontend-dev:
    build:
      context: ./dashboard-dev
      target: production
    restart: unless-stopped
    env_file:
      - ./dashboard-dev/.env
    networks:
      - jen-app
# staging services
  api-staging:
    build:
      context: ./api-staging
      target: production
    restart: unless-stopped
    env_file:
      - ./api-staging/.env
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - jen-app

  frontend-staging:
    build:
      context: ./dashboard-staging
      target: production
    restart: unless-stopped
    env_file:
      - ./dashboard-staging/.env
    networks:
      - jen-app

networks:
  jen-app:
    driver: bridge