name: deployer
services: 
  frontend:
    build:
      context: ./frontend
      target: production
      args:
        VITE_API_URL: https://api.${DOMAIN_NAME}
    restart: unless-stopped
    networks:
      - jen-app

networks:
  jen-app:
    driver: bridge
