name: deployer
services: 
  frontend-dev:
    build:
      context: ./dashboard-dev
      dockerfile: DockerFile
      target: production
    restart: unless-stopped
    env_file:
      - ./dashboard-dev/.env
  
  bsc:
    build:
      context: ./bsc
      dockerfile: DockerFile
      target: production
    restart: unless-stopped
    env_file:
      - ./bsc/.env
    networks:
      - jen-app
networks:
  jen-app:
    driver: bridge