# Use the official Jenkins LTS image
FROM jenkins/jenkins:lts

# User root to install Docker and Docker Compose
USER root

# Install required dependencies (curl, Docker, Docker Compose)
RUN apt-get update && apt-get install -y \
    jq \
    curl \
    ca-certificates \
    gnupg \
    lsb-release \
    sudo \
    nano \
    unzip \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && curl -fsSL https://get.docker.com -o get-docker.sh \
    && sh get-docker.sh \
    && curl -L $(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .assets[0].browser_download_url) -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

# Add the Jenkins user to the docker group
RUN usermod -aG docker jenkins

# Clean up unnecessary files
RUN apt-get clean && rm -rf /var/lib/apt/lists/*


